import type { FireflyConfig } from "#/infrastructure/config/schema";

export default {
    name: "firefly",
    scope: "yehezkieldio",
    base: "",
    repository: "yehezkieldio/firefly",
    changelogPath: "CHANGELOG.md",
    verbose: false,
    dryRun: false,
    bumpStrategy: "auto",
    preReleaseId: "",
    preReleaseBase: 0,
    releaseNotes: "",
    commitMessage: "chore(release): release {{name}}@{{version}}",
    tagName: "{{name}}@{{version}}",
    branch: "main",
    releaseTitle: "{{name}}@{{version}}",
    releaseLatest: true,
    releasePreRelease: false,
    releaseDraft: false,
    skipBump: false,
    skipChangelog: false,
    skipGitHubRelease: false,
    skipCommit: false,
    skipTag: false,
    skipPush: false,
} satisfies FireflyConfig;
